import os
import logging
import time
import google.generativeai as genai

logger = logging.getLogger(__name__)

EDITOR_PROMPT = """
You are the Executive Editor and Chief Compliance Officer for a major global publishing brand.
Your job is to strictly review content generated by a junior copywriter before it is published to the public.

You must review the provided content for:
1. **Safety & Compliance:** Does it contain hate speech, promote illegal acts, or violate standard social media community guidelines?
2. **Political Neutrality & Bias:** Is the content politically biased, highly controversial, or polarizing? It MUST remain objective and neutral.
3. **Misinformation:** Are there obvious hallucinations or fake claims?
4. **Quality:** Is the content actually engaging and well-formatted?

**YOUR ACTION:**
If the content is 100% safe, neutral, and high quality, simply output the EXACT original content without any changes.
If the content has minor issues (e.g., slight bias, an inappropriate joke), REWRITE the offending sections to make it safe, then output the fully corrected content.
If the content is completely unsalvageable or promotes highly dangerous/illegal things, output EXACTLY the phrase: "REJECTED_UNSAFE"

DO NOT output any conversational text like "Here is the corrected version". Output ONLY the final, safe markdown content.
"""

def edit_content(draft_content: str) -> str:
    """
    Passes the draft content to the Editor AI for review and revision.
    Returns the approved/edited content, or raises an Exception if rejected.
    """
    logger.info("Passing draft content to the Editor AI for verification...")
    
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        logger.error("GEMINI_API_KEY environment variable is not set.")
        raise ValueError("GEMINI_API_KEY is required to edit content.")

    genai.configure(api_key=api_key)
    
    selected_model_name = 'gemini-1.5-flash'
    try:
        for m in genai.list_models():
            if 'generateContent' in m.supported_generation_methods:
                selected_model_name = m.name.replace('models/', '')
                if 'flash' in selected_model_name:
                    break
    except Exception as e:
        logger.warning(f"Could not list models, defaulting to {selected_model_name}: {e}")

    model = genai.GenerativeModel(selected_model_name)
    
    prompt = f"Here is the draft content to review:\n\n{draft_content}"
    
    max_retries = 3
    for attempt in range(max_retries):
        try:
            response = model.generate_content(
                contents=[
                    {"role": "user", "parts": [{"text": EDITOR_PROMPT}]},
                    {"role": "user", "parts": [{"text": prompt}]}
                ]
            )
            
            final_content = response.text.strip()
            
            if final_content == "REJECTED_UNSAFE":
                logger.error("Editor AI rejected the content for safety violations.")
                raise ValueError("Content was rejected by the Editor AI for safety/bias violations.")
                
            logger.info("Editor AI successfully reviewed and approved the content.")
            return final_content
            
        except Exception as e:
            if "429" in str(e) and attempt < max_retries - 1:
                logger.warning(f"Rate limit hit during editing (429). Waiting 60 seconds before retry {attempt + 1}/{max_retries}...")
                time.sleep(60)
            else:
                logger.error(f"Error during Editor AI review: {e}")
                raise

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    test_draft = "# This is a draft post\nIt is completely fine and neutral."
    try:
        print(edit_content(test_draft))
    except Exception as ex:
        print(f"Failed: {ex}")
